sonar.projectKey=longtoz_yas-storefront
sonar.organization=longtoz
sonar.projectName=yas-storefront

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,test-results/**,.next/**,**/*.test.ts,**/*.test.tsx,jest.config.js,jest.setup.js,next.config.js
sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
