ui:
  image:
    repository: baohuyhuy/yas-backoffice-ui
    tag: main
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: true
    host: backoffice.yas.local.com
    path: /
    pathType: Prefix