name: security - snyk vulnerability scan

on:
  push:
    branches: ['main']
    paths:
      - '**/pom.xml'
      - '.github/workflows/security-snyk.yaml'
  pull_request:
    branches: ['main']
    paths:
      - '**/pom.xml'
      - '.github/workflows/security-snyk.yaml'
  schedule:
    - cron: '0 1 * * 1' # Every Monday at 01:00 UTC
  workflow_dispatch:

jobs:
  Snyk:
    name: Snyk Vulnerability Scan (all services)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - uses: ./.github/workflows/actions

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk vulnerability scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          find . -name "mvnw" -exec chmod +x {} +

          snyk test --severity-threshold=high \
            --file=pom.xml \
            --all-projects \
            -d \
            --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: snyk.sarif
